### ISSUE TITLE
json not saved

### ISSUE THREAD

**Issue by apasccon** [dfsq/json-server-init#2]
The script is not working, this is the output after running:

dev.json not saved: native promise missing, set Fetch.Promise to your favorite alternative

My npm version is 1.3.10.

**Comment by dfsq** [comment]
Yea.. Missed that. What is your nodejs version?

**Comment by apasccon** [comment]
nodejs v0.10.25

**Comment by apasccon** [comment]
My bad!, I was using a really old version of node. I forgot to update the symbolic link to a newer version:

sudo ln -sf /usr/local/n/versions/node/5.4.0/bin/node /usr/bin/node

Sorry for the confusion.

**Comment by dfsq** [comment]
Still this is the issue, since json-server-init uses Promise polifill for older node versions. Will need to fix it.
